# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 46aa480422785ecec33939fc796ca88753bc448c6204e3228b58ba772560c1aeff8f7bf31e8149dd8bc76349b76b238ce87540c00f73a8700fe6f82de4485775

test:
  secret_key_base: 86620f98ee090bf6bc0a6793713ee924d4a8ae59612065cf196a41592944643d16d180a8de39dbba5ab2a18bf20b0ae9c83b3404dc260b9e5dd2bd5a663c71cf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
